{{- if .Values.podDisruptionBudget.enabled }}
{{- range $component := list "control-api" "dashboard" }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "blue.fullname" $ }}-{{ $component }}
spec:
  minAvailable: {{ $.Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "blue.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $component }}
---
{{- end }}
{{- if .Values.blue.enableInferenceProxy }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "blue.fullname" . }}-inference-proxy
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "blue.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: inference-proxy
{{- end }}
{{- end }}
