//! Per-agent native certification through a REAL gateway (opt-in, secret-gated).
//!
//! This ports the old `End-to-end / Agent <name>` certification jobs into the
//! slim suite, driving **real inference** through a real inference-proxy → real
//! LiteLLM → OpenRouter (the OpenRouter key is a GitHub Actions secret). Every
//! agent is certified by the SAME `certify_agent` body, so no agent is tested
//! more or less than another.
//!
//! Each `<agent>_certifies` test:
//!   1. `blue apply --yes` — asserts the managed `e2e-remote` MCP server and the
//!      managed `example` skill are wired into that agent's config.
//!   2. `blue run <agent>` with a tool-forcing prompt — asserts exit 0, the
//!      `mcp-started` + `mcp-called` component markers, and `BLUE_MCP_OK` in the
//!      output (the marker the managed MCP tool returns). This proves the agent
//!      really launched, the MCP server started and was called, and a real model
//!      round-trip completed.
//!   3. LiteLLM spend logs — asserts this test's user (every test runs as its
//!      own unique user) produced an inference that resolved to the governed
//!      upstream model, and that the recorded credential is a hashed virtual
//!      key, not the inference JWT the agent sent (proof the proxy
//!      performed the swap).
//!
//! Self-skips without the gateway env (so the secret-free slim run is untouched),
//! and skips a given agent when its CLI is not installed (`NotEligible`).
//!
//! ## Version matrix (Tier B — the full certification grid)
//!
//! The cases below are generated by `build.rs`: one `<agent>_<ver>_certifies()`
//! per `(agent, version)` cell — the current lock pin (newest/blessed) plus every
//! historical sample in `agents.matrix.json`. Every generated cell runs the SAME
//! `certify_cell` body (a real OpenRouter round-trip), so no version is certified
//! more or less than another, and all stay in this `agent_certification` binary ⇒
//! the `gateway` profile + the `test(certifies)` retry override apply to each.
//!
//! Binary selection is by `PATH`: `run.sh` installs each cell into its own prefix
//! and records the bin dirs in the `E2E_SLIM_AGENT_MATRIX` manifest; the cell
//! prepends its bin dir so `blue` version-selects that exact CLI build. The lock
//! pin still certifies with the inherited `PATH` even when the matrix is off, so
//! today's coverage is preserved unchanged.

mod common;

use std::path::Path;
use std::time::Duration;

use e2e_slim::{AgentMatrix, AgentSelection, Home};

/// The current lock-pin version for `agent` (the newest/blessed cell). Read from
/// the shared lock so it tracks the single source of truth for the pin.
fn lock_pin_version(agent: &str) -> String {
    let lock = read_agents_json("agents.lock.json");
    lock.pointer(&format!("/agents/{agent}/version"))
        .and_then(serde_json::Value::as_str)
        .unwrap_or_else(|| panic!("agents.lock.json has no version for {agent}"))
        .to_owned()
}

fn read_agents_json(file: &str) -> serde_json::Value {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join(file);
    serde_json::from_slice(
        &std::fs::read(&path).unwrap_or_else(|error| panic!("reading {}: {error}", path.display())),
    )
    .unwrap_or_else(|error| panic!("parsing {}: {error}", path.display()))
}

/// Build the launch args for the `(agent, version)` cell — from the lock when it
/// is the pin, otherwise from `agents.matrix.json` — swapping the canned prompt
/// (the `BLUE_CERT_OK` element) for a tool-forcing one so the run exercises the
/// managed MCP tool.
fn cell_args(agent: &str, version: &str, is_pin: bool, prompt: &str) -> Vec<String> {
    let raw = if is_pin {
        read_agents_json("agents.lock.json")
            .pointer(&format!("/agents/{agent}/arguments"))
            .and_then(serde_json::Value::as_array)
            .cloned()
            .unwrap_or_else(|| panic!("no locked arguments for {agent}"))
    } else {
        let matrix = read_agents_json("agents.matrix.json");
        let versions = matrix
            .pointer(&format!("/agents/{agent}/versions"))
            .and_then(serde_json::Value::as_array)
            .unwrap_or_else(|| panic!("no matrix versions for {agent}"));
        versions
            .iter()
            .find(|entry| entry.get("version").and_then(serde_json::Value::as_str) == Some(version))
            .and_then(|entry| entry.get("arguments").and_then(serde_json::Value::as_array))
            .cloned()
            .unwrap_or_else(|| panic!("no matrix arguments for {agent} {version}"))
    };
    raw.iter()
        .map(|value| {
            let arg = value.as_str().unwrap_or_default().to_owned();
            // The canned human prompt is the element mentioning BLUE_CERT_OK.
            if arg.contains("BLUE_CERT_OK") {
                prompt.to_owned()
            } else {
                arg
            }
        })
        .collect()
}

/// Wait for the real agent's detached session-upload worker, then prove the
/// completed artifact belongs to this invocation without depending on any
/// agent-specific transcript structure.
fn assert_session_uploaded(home: &Home, agent: &str, nonce: &str) {
    let id = e2e_slim::wait_for(
        &format!("completed {agent} session upload"),
        Duration::from_secs(60),
        || {
            let items = home
                .list_session_uploads(25)
                .get("items")
                .and_then(serde_json::Value::as_array)
                .cloned()
                .unwrap_or_default();
            items.into_iter().find_map(|item| {
                if item.get("harness").and_then(serde_json::Value::as_str) != Some(agent) {
                    return None;
                }
                let id = item.get("id").and_then(serde_json::Value::as_str)?;
                let detail = home.get_upload(id);
                detail
                    .get("artifacts")
                    .and_then(serde_json::Value::as_array)
                    .is_some_and(|artifacts| {
                        artifacts.iter().any(|artifact| {
                            artifact.get("status").and_then(serde_json::Value::as_str)
                                == Some("complete")
                        })
                    })
                    .then(|| id.to_owned())
            })
        },
    );

    // The stored artifact is a portable session bundle (gzip tar), so unpack it
    // and search the archived transcript bodies — grepping the compressed blob
    // would never match.
    let bundle = e2e_slim::parse_session_bundle(&home.download_upload(&id));
    assert!(
        bundle.any_file_contains(nonce.as_bytes()) || bundle.any_file_contains(b"BLUE_MCP_OK"),
        "{agent}: uploaded session bundle is not attributable to this invocation: \
         expected nonce `{nonce}` or BLUE_MCP_OK in {} archived file(s): {}",
        bundle.files.len(),
        bundle.manifest
    );
}

/// Certify one `(agent, version)` matrix cell through the real gateway.
///
/// Skips (returns) when the gateway env is unset. For a **sample** cell it also
/// skips unless `run.sh` installed it and recorded its bin dir in the matrix
/// manifest. The **pin** cell still certifies with the inherited `PATH` when the
/// matrix is off, preserving today's per-agent certification unchanged.
fn certify_cell(agent: &str, version: &str) {
    let Some(gateway) = e2e_slim::gateway_env_or_skip() else {
        eprintln!("gateway stack env unset; skipping {agent} {version} certification");
        return;
    };

    let is_pin = version == lock_pin_version(agent);
    let bin_dir = AgentMatrix::from_env().and_then(|matrix| matrix.bin_dir(agent, version));
    if bin_dir.is_none() && !is_pin {
        eprintln!(
            "{agent} {version}: no matrix bin dir (E2E_SLIM_AGENT_MATRIX unset or cell absent); \
             skipping"
        );
        return;
    }

    let upstream_model = common::AGENTS
        .iter()
        .find(|(name, _)| *name == agent)
        .map(|(_, model)| *model)
        .unwrap_or_else(|| panic!("unknown agent {agent}"));

    let home = gateway.bootstrap_gateway_home_pinned(bin_dir);

    if home.select_agent(agent) == AgentSelection::NotEligible {
        eprintln!("{agent} {version} CLI not installed/eligible; skipping certification");
        return;
    }

    // (1) Config-level: apply wires the managed MCP server + skill in.
    home.blue().args(["apply", "--yes"]).assert().success();
    common::assert_mcp_registered(&home, agent);
    common::assert_example_skill_materialized(&home, agent);

    // (2) Launch the real agent through the gateway and force the managed tool.
    let nonce = format!("BLUE_E2E_INVOCATION_{}", uuid::Uuid::new_v4());
    let prompt = format!(
        "Invocation marker: {nonce}. Use the blue_certify MCP tool now, then reply with exactly \
         the tool's returned text and nothing else."
    );
    let output = home.run_agent(agent, &cell_args(agent, version, is_pin, &prompt));
    let combined = format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(
        output.status.success(),
        "`blue run {agent}` exited non-zero:\n{combined}"
    );
    let markers = Path::new("/tmp/blue-e2e/component-markers");
    assert!(
        markers.join("mcp-started").is_file(),
        "{agent}: mcp-started marker missing (MCP server never launched):\n{combined}"
    );
    assert!(
        markers.join("mcp-called").is_file(),
        "{agent}: mcp-called marker missing (managed MCP tool never invoked):\n{combined}"
    );
    assert!(
        combined.contains("BLUE_MCP_OK"),
        "{agent}: output missing the BLUE_MCP_OK MCP marker:\n{combined}"
    );

    // (3) The native shutdown hook spools asynchronously, so after the agent
    // exits poll until this unique test user's real transcript is complete.
    assert_session_uploaded(&home, agent, &nonce);

    // (4) Real inference from THIS test's unique user hit the gateway and
    //     resolved to the governed upstream model, and the proxy swapped the
    //     inference JWT for a hashed virtual key. LiteLLM's spend log records the
    //     resolved upstream model (e.g. `openrouter/openai/gpt-5.6-terra`), not
    //     the name the agent requested, so match on a substring.
    let entry = gateway.spend_log_for_user(home.email());
    let logged_model = entry
        .get("model")
        .and_then(serde_json::Value::as_str)
        .unwrap_or_default();
    assert!(
        logged_model.contains(upstream_model),
        "{agent}: spend log should record the governed upstream model \
         `{upstream_model}`, got `{logged_model}`: {entry}"
    );
    let api_key = entry
        .get("api_key")
        .and_then(serde_json::Value::as_str)
        .unwrap_or_default();
    assert_ne!(
        api_key.split('.').count(),
        3,
        "{agent}: spend log recorded the inference JWT, not a swapped virtual key: {entry}"
    );
}

// The expected upstream model per agent lives in `common::AGENTS` — the
// OpenRouter deployment its governed model maps to in
// fixtures/litellm-config.yaml. Each expectation is a substring of the resolved
// deployment id the spend log records (e.g. `openrouter/moonshotai/kimi-k2.6`
// for kimi's bare `kimi-k2.6`).

// One `#[test] fn <agent>_<ver>_certifies()` per matrix cell — the full grid,
// including the lock-pin cell per agent (which preserves today's per-agent
// certification coverage).
include!(concat!(env!("OUT_DIR"), "/matrix_cert_cases.rs"));
