//! Tier A — the **config** version matrix (free, governance path, every PR).
//!
//! One case per `(agent, version)` cell (generated by `build.rs` from
//! `agents.lock.json` + `agents.matrix.json`): pin the installed CLI build via
//! `PATH`, run `blue apply --yes`, and assert the same managed model, MCP server,
//! and skill land as the single-version `all_agents_config` / `claude_config`
//! tests do — but across multiple CLI versions. No inference, so this runs even
//! on fork PRs where the gateway secret (and thus the paid cert matrix) is absent.
//!
//! Named so it lands in the `governance` nextest profile automatically
//! (`not binary(agent_certification)`), and deterministic ⇒ no retries.
//!
//! Every case self-skips when the matrix manifest (`E2E_SLIM_AGENT_MATRIX`, set by
//! `run.sh` under `E2E_SLIM_MATRIX=1`) is absent, so the lock-pin coverage already
//! provided by `all_agents_config` / `claude_config` is never duplicated when the
//! matrix is off — no behavior change with the matrix disabled.

mod common;

use std::path::Path;

use e2e_slim::{AgentMatrix, AgentSelection};

/// Shared body: pin the cell's CLI build, apply, and assert managed config.
fn matrix_managed_config(agent: &str, version: &str) {
    let Some(stack) = e2e_slim::env_or_skip() else {
        return;
    };
    let Some(matrix) = AgentMatrix::from_env() else {
        // Matrix off: the lock pin is already covered by all_agents_config /
        // claude_config, and samples aren't installed. Nothing to do.
        return;
    };
    let Some(bin_dir) = matrix.bin_dir(agent, version) else {
        eprintln!("{agent} {version}: no matrix bin dir; skipping");
        return;
    };

    let home = stack.bootstrap_home_pinned(Some(bin_dir));
    if home.select_agent(agent) == AgentSelection::NotEligible {
        eprintln!("{agent} {version} CLI not installed/eligible; skipping");
        return;
    }

    home.blue().args(["apply", "--yes"]).assert().success();
    let model = model_for(agent);
    common::assert_governed_model(&home, agent, model);
    common::assert_mcp_registered(&home, agent);
    common::assert_example_skill_materialized(&home, agent);
    drop(home); // Native state and asynchronous children must be clean before recording success.
    e2e_slim::record_cell("governance", agent, version);
}

/// The governed model a given agent's managed config must carry, from the shared
/// `common::AGENTS` table (so the matrix never drifts from the single-version
/// tests on which model each agent is governed to).
fn model_for(agent: &str) -> &'static str {
    common::AGENTS
        .iter()
        .find(|(name, _)| *name == agent)
        .map(|(_, model)| *model)
        .unwrap_or_else(|| panic!("unknown agent {agent}"))
}

/// Data-integrity guard (runs with no stack, on every profile): the matrix must
/// only carry EXTRA historical samples — never re-list the lock pin, which
/// `build.rs` already adds as its own cell. Catches drift when the lock advances.
#[test]
fn matrix_excludes_lock_pin() {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let lock = common::read_json(&manifest_dir.join("../e2e/agents.lock.json"));
    let matrix = common::read_json(&manifest_dir.join("agents.matrix.json"));
    for (agent, _) in common::AGENTS {
        let pin = lock
            .pointer(&format!("/agents/{agent}/version"))
            .and_then(serde_json::Value::as_str)
            .unwrap_or_else(|| panic!("agents.lock.json has no version for {agent}"));
        if let Some(versions) = matrix
            .pointer(&format!("/agents/{agent}/versions"))
            .and_then(serde_json::Value::as_array)
        {
            for entry in versions {
                let version = entry.get("version").and_then(serde_json::Value::as_str);
                assert_ne!(
                    version,
                    Some(pin),
                    "{agent}: agents.matrix.json duplicates the lock pin {pin}; \
                     the pin is added automatically — list only older samples"
                );
            }
        }
    }
}

// One `#[test] fn <agent>_<ver>_managed_config()` per matrix cell.
include!(concat!(env!("OUT_DIR"), "/matrix_config_cases.rs"));
